### ISSUE TITLE
[BUG] More than one possible candidate for "$x" call

### ISSUE THREAD

**Issue by noname0310** [GoogleFeud/ts-macros#20]
**Describe the bug**
I think this code has enough information(this) to specify the method. Why not?

**Code to reproduce**

code:
```typescript
export namespace Vector2 {
    export namespace Methods {
        export function $asData(v: Vector2): [number, number] {
            return v as unknown as [number, number];
        }

        export function $x(self: Vector2): number {
            return $asData(self)[0];
        }

        export function $y(self: Vector2): number {
            return $asData(self)[1];
        }
    }
    
    export function $from(x: number, y: number): Vector2 {
        return [x, y] as unknown as Vector2;
    }
}

interface Vector2 {
    $x(): number;
    $y(): number;
}

export namespace Vector3 {
    export namespace Methods {
        export function $asData(v: Vector3): [number, number, number] {
            return v as unknown as [number, number, number];
        }

        export function $x(self: Vector3): number {
            return $asData(self)[0];
        }

        export function $y(self: Vector3): number {
            return $asData(self)[1];
        }
    }

    export function $from(x: number, y: number, z: number): Vector3 {
        return [x, y, z] as unknown as Vector3;
    }
}

interface Vector3 {
    $x(): number;
    $y(): number;
    $z(): number;
}

const v2 = Vector2.$from!(1, 2);
console.log(v2.$x!(), v2.$y!());
```

error: 
```
src/index.ts:53:13 - error TS8000: More than one possible candidate for "$x" call

53 console.log(v2.$x!(), v2.$y!());
```

**Expected behavior**

```typescript
const v2 = [1, 2];
console.log(v2[0], v2[1]);
```

**Additional context**

**Comment by GoogleFeud** [comment]
The code currently uses a `typescript` provided function to compare types and check if they're "assignable" to another. `Vector3` is assignable to `Vector2` because `Vector3` has all the properties `Vector2` needs (`$x` and `$y`).

You can fix this you can brand the `Vector2` type:
```ts
interface Vector2 {
    _type: "vector2";
    $x(): number;
    $y(): number;
}
```

[Playground](https://googlefeud.github.io/ts-macros/playground/?code=FAUwHgDg9gTgLgAgHYEMC2IDOEUGMQIBqIucsATAgN7AJ0LjTzLpY74ICyIcAFlABNM1WvTGNYiAGYBXJKQCWUJAgAkKTABEUcFAAoAbgC4iJMjHIBKEwG0kMtACMQMADTIHzmAF0RY--QwPDIwKgYIGghyANZIUADuKpF2ni7u9k4u3gDcogEAvsB5-hLMsvJwSiqqYHqYIAA2UibEpBTWHpkwfgH+QXAh1RraugCEdY1SljYADDnFYoUL9KXScorKagCeE00tZu0mGV49vYHBoWrDOijj9U3TAIzzZ4WLxcWrCOUb1VIwUDQejAR1SbgQW1BXQ6rXMlBoZ36gwQNjA7i2vkiMTiiQiwlhFFy7yWCiQcBcUjwBAJFlOCAA+nAthAQCYAEQGA4WNlE+g1PQdY4uXl0VQ7QVg3JLL6oDDYKmmNowADMdJlrHlHG4fEEwgRvS+P0qm3UWhuhn2SuVHRSXXSYPtXV8+rOdCRl3CWKQsQSSWEtq8jsDnS8L16SzOhvWxuqtXuzUV5mtUJOLtd7qGZrGuymszDBSKkcgkm+0aq2xzlqTEq6dMRF0zI1uOae+f8b3oEZWxbKZZN-0BwJTaQhw-BAC8xzCuaq02IMyi0RD3OPMcJsb68YnYMqRQhCiSyRSFTTZ8VGczWQgOTO2cV+TWvHuxQKx8-x6+Q8LgEtcMpMIgBiUAAvNuFgAHSqAOaDjI87hWLkf5IJgUANCA4ENFAADmhjkJBYDjJY7hAZBWyEZY2RAA)

**Comment by noname0310** [comment]
Thank you!

I think it would be better to include information about this in the document.
