### ISSUE TITLE
[FEATURE] Expose MacroError for consumers

### ISSUE THREAD

**Issue by tusharmath** [GoogleFeud/ts-macros#32]
**Is your feature request related to a problem? Please describe.**
`MacroError` is a fantastic way of telling the user what the error. I think if someone is writing custom macros, they should be able to throw using `MacroError`.

**Describe the solution you'd like**
```ts
import {MacroError} from 'ts-macro'

function $justThrow() {
  $$raw((ctx) => {
    throw MacroError(ctx, "This just fails")
  })
}
```

**Describe alternatives you've considered**
I have copy pasted all the code from the library to throw an error from my macro.

**Additional context**
None

**Comment by GoogleFeud** [comment]
This is a great idea! Although I'll have to attach the `MacroError` function to the `ctx` object because otherwise, it won't work. I'll add this in the next update!

I've also made errors coming from `$$raw` and `$$comptime` prettier, so if you decide to `throw new Error(...)` in `$$raw` it'll display like this:

![Capture](https://user-images.githubusercontent.com/36000090/212498010-9d6c97a6-ca28-4742-97e5-3cbdffd4bb5e.PNG)
