### ISSUE TITLE
[BUG]: Macro expansion fails when defined inside objects

### ISSUE THREAD

**Issue by tusharmath** [GoogleFeud/ts-macros#37]
**Describe the bug**
If there is a method that is defined on an object literal which uses `$$raw` there the expansion fails.

**Code to reproduce**
```ts
const Foo = {
    $bar() {
         $$raw!((ctx) => {
            return ctx.factory.createStringLiteral("Yello!")
        })
    }
}

Foo.$bar!()
```
**Expected behavior**
Macro expansion to succeed. Instead one gets the following error 

```
Error: `raw` macro must be called inside another macro.
```

**Additional context**
None

**Comment by GoogleFeud** [comment]
Hello! This is the intended behavior because a macro is not associated with any object. You can instead do something like this:
```ts
type ObjectType = {
    property: string,
    $bar() : string
}

function $bar(obj: ObjectType) {
    $$raw!((ctx, objNode: any) => {
        return ctx.factory.createStringLiteral("Yello!");
    });
}

const obj = {
    property: "Hello!"
} as ObjectType;

console.log(obj.$bar!());
```
playground: https://googlefeud.github.io/ts-macros/playground/?code=FAFwngDgpgBA8gIwFZQMYgCqVgXhgb2BmJggCcB7aM8ALhgGcQyBLAOwHMAaIkgEgQBDMgAoAlDHpNWnYAF9gwAGYBXNuhYU2MAcJEVk9RCnRZoEwiRhkoIFWW18+ZQQHcAhCJHoAHlxgGSAByFAAmUPSCbGASOAB8BLxWxDZ2DjC+AHRKgugUZGCZqDaCIFAAyszsHAAyLGUuADYiAEQAmlCNjRTuLWIA3EkwcgPyiqhaTAHIMHiWJORUUDRg9C0AEp3dvfIwggzwyGiY2IPAE2wMFI1Qmd0c+siZumSeYgNAA
