### ISSUE TITLE
[BUG]different results when file is split

### ISSUE THREAD

**Issue by noname0310** [GoogleFeud/ts-macros#8]
**Describe the bug**
Splitting files generates strange code.

**Code to reproduce**

input
```typescript
// src/Vector2.ts
export namespace Vector2 {
    export function $new(): Vector2 {
        return [0, 0] as unknown as Vector2;
    }

    export function $from(x: number, y: number): Vector2 {
        return [x, y] as unknown as Vector2;
    }
}

export interface Vector2 {
    $x(): number;
    $y(): number;
}

function $asData(v: Vector2): [number, number, number] {
    return v as unknown as [number, number, number];
}

export function $x(v: Vector2): number {
    return $asData!(v)[0];
}

export function $y(v: Vector2): number {
    return $asData!(v)[1];
}
```
```typescript
// src/index.ts
import { Vector2 } from '../Vector2';

const vec1 = Vector2.$new!();
console.log(vec1.$x!());
console.log(vec1.$y!());

const vec2 = Vector2.$from!(1, 2);

export {}
```

output
```javascript
// src/Vector2.js
export var Vector2;
(function (Vector2) {
})(Vector2 || (Vector2 = {}));
```

```javascript
// src/index.js
import { Vector2 } from '../Vector2';
const vec1 = [v, c1];
console.log(vec1[]);
console.log(vec1[]);
const vec2 = [Vector2, 1];
```

**Expected behavior**
```javascript
// src/index.js
import { Vector2 } from '../Vector2';
const vec1 = [0, 0];
console.log(vec1[0]);
console.log(vec1[1]);
const vec2 = [1, 2];
```

**Additional context**
If i don't split the file, the Expected Behavior will come out properly.

I'm sorry for making an issue again even though it hasn't been long since you patched :[

**Comment by GoogleFeud** [comment]
Thanks for the issue, this is actually a pretty big deal that I've overlooked - the typescript compiler saves memory by not saving literal values (number values, strings, identifiers, etc.) and instead it uses the tokens' position to get the value when it's requested. It tries to get the values of the number tokens which are in another file, so the characters at the positions are different (in this case `0, 0` in `src/vector` is `vec1` in `src/index` - `0`-> `v`, `(empty space)0` -> `c1`)

Since this is a very serious issue I'll fix it ASAP and make a new relase for it :)!

**Comment by noname0310** [comment]
it make sense, I look forward to the next release :D
